EXPT_NAME theanolm-100k
EXPT_PARAMS expt10-seed3
EXPT_WORK_DIR /scratch/work/moisioa3/conv_lm/experiments/theanolm-100k/expt10-seed3
Experiment: theanolm-100k/expt10-seed3
Job ID: 54705165
Task ID: 60
Host: gpu9.int.triton.aalto.fi
Start date: Mon Jul 13 22:22:07 EEST 2020
Work directory: /scratch/work/moisioa3/conv_lm/experiments/theanolm-100k/expt10-seed3
Temporary directory: /tmp/54705165

Currently Loaded Modules:
  1) speech-scripts/2016.05.24-b928230   6) binutils/2.25-GCCcore-5.4.0
  2) srilm/default                       7) GCC/5.4.0-2.25
  3) cuda/10.0.130                       8) libgpuarray/2017.03.29-45c731f
  4) cudnn/7.4.2-cuda                    9) anaconda3/latest
  5) GCCcore/5.4.0

 

/tmp/54705165/lattices
floatX=float32,device=cuda0,base_compiledir=/tmp/theano,exception_verbosity=high,openmp=False
INFO (theano.gof.compilelock): Waiting for existing lock by process '208191' (I am process '208872')
INFO (theano.gof.compilelock): To manually release the lock, delete /tmp/theano/compiledir_Linux-3.10-el7.x86_64-x86_64-with-centos-7.8.2003-Core-x86_64-3.7.3-64/lock_dir
/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/theano/gpuarray/dnn.py:184: UserWarning: Your cuDNN version is more recent than Theano. If you encounter problems, try updating Theano or downgrading cuDNN to a version >= v5 and <= v7.
  warnings.warn("Your cuDNN version is more recent than "
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/theano/gpuarray/__init__.py", line 227, in <module>
    use(config.device)
  File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/theano/gpuarray/__init__.py", line 214, in use
    init_dev(device, preallocate=preallocate)
  File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/theano/gpuarray/__init__.py", line 99, in init_dev
    **args)
  File "pygpu/gpuarray.pyx", line 658, in pygpu.gpuarray.init
  File "pygpu/gpuarray.pyx", line 587, in pygpu.gpuarray.pygpu_init
pygpu.gpuarray.GpuArrayException: b'cuDevicePrimaryCtxRetain: CUDA_ERROR_ECC_UNCORRECTABLE: uncorrectable ECC error encountered'
TheanoLM 1.3.2
Theano 1.0.4
pygpu 0.7.6
==
+ srun --gres=gpu:1 theanolm decode /scratch/work/moisioa3/conv_lm/experiments/theanolm-100k/expt10-seed3/nnlm.h5 --lattice-list /tmp/54705165/lattices/lattice-list --output-file /scratch/work/moisioa3/conv_lm/experiments/theanolm-100k/expt10-seed3/decode/eval/lambda=0.5-lms=11/60.trn --output trn --nnlm-weight 0.5 --lm-scale 11 --max-tokens-per-node 62 --beam 650 --recombination-order 22 --num-jobs 128 --job 60 --shortlist --unk-penalty=-20
/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/theano/gpuarray/dnn.py:184: UserWarning: Your cuDNN version is more recent than Theano. If you encounter problems, try updating Theano or downgrading cuDNN to a version >= v5 and <= v7.
  warnings.warn("Your cuDNN version is more recent than "
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/theano/gpuarray/__init__.py", line 227, in <module>
    use(config.device)
  File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/theano/gpuarray/__init__.py", line 214, in use
    init_dev(device, preallocate=preallocate)
  File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/theano/gpuarray/__init__.py", line 99, in init_dev
    **args)
  File "pygpu/gpuarray.pyx", line 658, in pygpu.gpuarray.init
  File "pygpu/gpuarray.pyx", line 587, in pygpu.gpuarray.pygpu_init
pygpu.gpuarray.GpuArrayException: b'cuDevicePrimaryCtxRetain: CUDA_ERROR_ECC_UNCORRECTABLE: uncorrectable ECC error encountered'
2020-07-13 22:22:31,600 get_default_device: Theano is not using a GPU or an old version of libgpuarray is installed.
2020-07-13 22:22:31,600 from_file: Reading vocabulary from network state.
2020-07-13 22:22:34,229 from_file: Number of words in vocabulary: 2427252
2020-07-13 22:22:34,230 from_file: Number of words in shortlist: 100003
2020-07-13 22:22:34,230 from_file: Number of word classes: 100003
2020-07-13 22:22:34,230 from_file: Building neural network.
2020-07-13 22:23:09,628 from_file: Restoring neural network state.
2020-07-13 22:23:10,854 decode: Building word lattice decoder.
/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/h5py-2.9.0-py3.7-linux-x86_64.egg/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  "Use dataset[()] instead.", H5pyDeprecationWarning)
/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/h5py-2.9.0-py3.7-linux-x86_64.egg/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  "Use dataset[()] instead.", H5pyDeprecationWarning)
WARNING (theano.tensor.blas): We did not find a dynamic library in the library_dir of the library we use for blas. If you use ATLAS, make sure to compile it with dynamics library.
2020-07-13 22:23:20,876 _ldflags: We did not find a dynamic library in the library_dir of the library we use for blas. If you use ATLAS, make sure to compile it with dynamics library.
2020-07-13 22:23:21,304 exception_handler: An unexpected ImportError exception occurred: /share/apps2/anaconda/anaconda3/latest/lib/libmkl_intel_thread.so: undefined symbol: __kmpc_reduce_nowait
Traceback will be written to debug log (enable with --log-level debug).
srun: error: gpu9: task 0: Exited with exit code 2
srun: Terminating job step 54705165.0
++ echo Failed on line: 396 at command: '${run_gpu}' theanolm decode '"${EXPT_WORK_DIR}/nnlm.h5"' --lattice-list '"${lattices_file}"' --output-file '"${out_file}"' --output '"trn"' --nnlm-weight '"${nnlm_weight}"' --lm-scale '"${lm_scale}"' --max-tokens-per-node '"${max_tokens_per_node}"' --beam '"${beam}"' --recombination-order '"${recombination_order}"' --num-jobs '"${num_batches}"' --job '"${batch_index}"' '"${extra_args[@]}"'
Failed on line: 396 at command: ${run_gpu} theanolm decode "${EXPT_WORK_DIR}/nnlm.h5" --lattice-list "${lattices_file}" --output-file "${out_file}" --output "trn" --nnlm-weight "${nnlm_weight}" --lm-scale "${lm_scale}" --max-tokens-per-node "${max_tokens_per_node}" --beam "${beam}" --recombination-order "${recombination_order}" --num-jobs "${num_batches}" --job "${batch_index}" "${extra_args[@]}"
Failed on line: 327 at command: out_file="${out_dir}/${batch_index}.trn"
